import os
import yaml
import subprocess
import google.generativeai as genai
from dotenv import load_dotenv

# Load environment variables (for GEMINI_API_KEY)
load_dotenv()

# Configure Gemini
genai.configure(api_key=os.getenv("GEMINI_API_KEY"))
model = genai.GenerativeModel(model_name="gemini-1.5-flash")

# List of PRD YAML files to process
prd_files = [
    "prds/auth.yaml",
    "prds/movie-discovery.yaml",
    "prds/showtime-selection.yaml",
    "prds/seat-booking.yaml",
    "prds/payment.yaml",
    "prds/confirmation.yaml"
]

# Read the PRD YAML file
def read_prd(file_path):
    with open(file_path, 'r') as file:
        return yaml.safe_load(file)

# Ask Gemini to generate content based on prompt
def ask_gpt(prompt):
    response = model.generate_content(prompt)
    return response.text

# Save generated code to a file
def save_code(code, filename):
    os.makedirs("generated", exist_ok=True)
    file_path = os.path.join("generated", filename)
    with open(file_path, "w") as f:
        f.write(code)

# Create a Git branch, commit code, and open a PR using GitHub CLI
def commit_and_pr(branch_name, message):
    subprocess.run(["git", "checkout", "-b", branch_name], check=True)
    subprocess.run(["git", "add", "."], check=True)
    subprocess.run(["git", "commit", "-m", message], check=True)
    subprocess.run(["git", "push", "--set-upstream", "origin", branch_name], check=True)
    subprocess.run(["gh", "pr", "create", "--title", message, "--body", "Auto-generated by AI"], check=True)

# Main loop to process all PRDs
for prd_file in prd_files:
    prd = read_prd(prd_file)
    
    # Extract feature name and page name
    feature_name = prd.get("feature", "unknown-feature").lower().replace(" ", "-")
    page_name = prd["pages"][0]["name"]
    frontend_stack = prd['tech_stack']['frontend']
    description = prd['description']

    # Prepare prompt
    prompt = f"Create a {frontend_stack} page called {page_name} with the following functionality:\n{description}"
    
    # Get generated code
    code = ask_gpt(prompt)

    # Define file name and branch name
    filename = f"{page_name}.jsx"
    branch_name = f"feat/{feature_name}"
    commit_msg = f"feat: {page_name} page generated by AI"

    # Save, commit, and create PR
    save_code(code, filename)
    commit_and_pr(branch_name, commit_msg)












# import os
# import yaml
# import subprocess
# import google.generativeai as genai
# from dotenv import load_dotenv

# prd_files = [
#     "prds/auth.yaml",
#     "prds/movie-discovery.yaml",
#     "prds/showtime-selection.yaml",
#     "prds/seat-booking.yaml",
#     "prds/payment.yaml",
#     "prds/confirmation.yaml"
# ]

# load_dotenv()

# genai.configure(api_key=os.getenv("GEMINI_API_KEY"))

# model = genai.GenerativeModel(model_name="gemini-1.5-flash")

# def read_prd(file_path):
#     with open(file_path, 'r') as file:
#         return yaml.safe_load(file)

# def ask_gpt(prompt):
#     response = model.generate_content(prompt)
#     return response.text

# def save_code(code, filename):
#     os.makedirs("generated", exist_ok=True)
#     with open(f"generated/{filename}", "w") as f:
#         f.write(code)

# def commit_and_pr(branch_name, message):
#     subprocess.run(["git", "checkout", "-b", branch_name])
#     subprocess.run(["git", "add", "."])
#     subprocess.run(["git", "commit", "-m", message])
#     subprocess.run(["git", "push", "--set-upstream", "origin", branch_name])
#     subprocess.run(["gh", "pr", "create", "--title", message, "--body", "Auto-generated by AI"])

# # --- MAIN EXECUTION ---
# prd = read_prd("prds/login-flow.yaml")
# prompt = f"Create a {prd['tech_stack']['frontend']} login page with the following: {prd['description']}"
# code = ask_gpt(prompt)

# save_code(code, "LoginPage.jsx")
# commit_and_pr("feat/login-page", "feat: login page generated by AI")


# ===================================

# import os
# import yaml
# import subprocess
# import google.generativeai as genai
# from dotenv import load_dotenv
# load_dotenv()

# genai.configure(api_key=os.getenv("GEMINI_API_KEY"))

# model = genai.GenerativeModel("gemini-pro")

# def read_prd(file_path):
#     with open(file_path, 'r') as file:
#         return yaml.safe_load(file)

# def ask_gpt(prompt):
#     response = model.generate_content(prompt)
#     return response.text

# def save_code(code, filename):
#     os.makedirs("generated", exist_ok=True)
#     with open(f"generated/{filename}", "w") as f:
#         f.write(code)

# def commit_and_pr(branch_name, message):
#     subprocess.run(["git", "checkout", "-b", branch_name])
#     subprocess.run(["git", "add", "."])
#     subprocess.run(["git", "commit", "-m", message])
#     subprocess.run(["git", "push", "--set-upstream", "origin", branch_name])
#     subprocess.run(["gh", "pr", "create", "--title", message, "--body", "Auto-generated by AI"])

# # --- MAIN EXECUTION ---
# prd = read_prd("prds/login-flow.yaml")
# prompt = f"Create a {prd['tech_stack']['frontend']} login page with the following: {prd['description']}"
# code = ask_gpt(prompt)

# save_code(code, "LoginPage.jsx")
# commit_and_pr("feat/login-page", "feat: login page generated by AI")


# import os
# import yaml
# import subprocess
# from openai import OpenAI
# from dotenv import load_dotenv
# load_dotenv()

# client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

# def read_prd(file_path):
#     with open(file_path, 'r') as file:
#         return yaml.safe_load(file)

# def ask_gpt(prompt):
#     response = client.chat.completions.create(
#         model="gpt-3.5-turbo",
#         messages=[
#             {"role": "system", "content": "You are an expert React developer."},
#             {"role": "user", "content": prompt}
#         ]
#     )
#     return response.choices[0].message.content

# def save_code(code, filename):
#     os.makedirs("generated", exist_ok=True)
#     with open(f"generated/{filename}", "w") as f:
#         f.write(code)

# def commit_and_pr(branch_name, message):
#     subprocess.run(["git", "checkout", "-b", branch_name])
#     subprocess.run(["git", "add", "."])
#     subprocess.run(["git", "commit", "-m", message])
#     subprocess.run(["git", "push", "--set-upstream", "origin", branch_name])
#     subprocess.run(["gh", "pr", "create", "--title", message, "--body", "Auto-generated by AI"])

# # --- MAIN EXECUTION ---
# prd = read_prd("prds/login-flow.yaml")
# prompt = f"Create a {prd['tech_stack']['frontend']} login page with the following: {prd['description']}"
# code = ask_gpt(prompt)

# save_code(code, "LoginPage.jsx")
# commit_and_pr("feat/login-page", "feat: login page generated by AI")
